### ISSUE TITLE
Rename repo 'angular-infinite-scroll'

### ISSUE THREAD

**Issue by edoparearyee** [thisissoon/angular-infinite-scroll#1]
Just one comment I think I would name the repo angular-infinite-scroll so it’s clear that it is a angular module and for consistency with our other modules.

**Comment by jamesjwarren** [comment]
there is already a module on bower called `angular-infinite-scroll` so on bower I've called it `angular-sn-infinite-scroll` would it be better if the repo was renamed to be the same as the bower component?

**Comment by edoparearyee** [comment]
The repo doesn't have to be named the same, on bower you can add keywords to the bower config to help people search for it. Having sn in the name of the repo on our github doesn't make seem right as the repo is already name-spaced on github.

**Comment by jamesjwarren** [comment]
Fair point.
